### ISSUE TITLE
How-to guide?

### ISSUE THREAD

**Issue by notdon** [perlancar/perl-App-CekBpom#1]
Halo! ini library keren banget👍 banyak potensi nya. Tapi belom bisa nyobain karena gatau cara kerja nya di terminal kayak gimana. Cara run di terminal nya gimana ya??🙏🏽 makasih banyak!

**Comment by perlancar** [comment]
Diinstal aja seperti menginstal modul CPAN pada umumnya:

    % cpanm -n App::CekBpom

lalu nanti gunakan skrip cek-bpom-products. Manualnya ada di:
 
    https://metacpan.org/pod/cek-bpom-products
